ConvertFrom-StringData -StringData @'
UnsupportedOSBuild                        = このスクリプトは Windows 11 23H2 かそれ以上のバージョンをサポートしています
UpdateWarning                             = お使いの Windows 11 は build: {0}.{1}です。サポートされているのは builds: 22631.2792 かそれ以上です。Windows Update を実行してから再度お試しください。
UnsupportedLanguageMode                   = PowerShell は限られた言語モードで実行されています
LoggedInUserNotAdmin                      = ログオンしているユーザーには管理者権限がありません
UnsupportedPowerShell                     = PowerShell {0}.{1} でスクリプトを実行しようとしています。適切な PowerShell のバージョンで実行してください
UnsupportedHost                           = {0} でのスクリプトの実行はサポートされていません
Win10TweakerWarning                       = お使いの OS は Win 10 Tweaker のバックドアから感染した可能性があります
TweakerWarning                            = Windos の安定性が {0} で損なわれた可能性があります。念のため、OS を再インストールしてください
bin                                       = bin フォルダーの中にファイルがありません。再度、アーカイブをダウンロードしてください
RebootPending                             = PC は再起動の待機中です
UnsupportedRelease                        = 新しいバージョンが見つかりました
KeyboardArrows                            = キーボードの十字キーの {0} と {1} を使用して、回答を選択してください。
CustomizationWarning                      = Sophia Script を実行する前に {0} プリセットファイル内の各機能を好みに合わせて変更しましたか？
WindowsComponentBroken                    = {0} が破損しているか OS から削除されている可能性があります
UpdateDefender                            = Microsoft Defender の定義が最新ではありません。Windows Update を実行してから再度お試しください。
ControlledFolderAccessDisabled            = 制御されたフォルダー アクセスが無効になっています
InitialActionsCheckFailed                 = {0} プリセットファイルから "InitialActions" 関数を読み込めませんでした
ScheduledTasks                            = スケジュールされたタスク
OneDriveUninstalling                      = OneDrive をアンインストールしています...
OneDriveInstalling                        = OneDrive をインストールしています...
OneDriveDownloading                       = OneDrive をダウンロードしています...
OneDriveWarning                           = "{0}" 関数は、OneDrive を削除するようプリセットで設定されている場合に限り適用されます（またはアプリが既に削除されている場合）、さもなければ、OneDrive 内の "デスクトップ" と "ピクチャ" フォルダーのバックアップ機能が停止します
WindowsFeaturesTitle                      = Windows の機能
OptionalFeaturesTitle                     = オプション機能
EnableHardwareVT                          = UEFI で「ハードウェアの仮想化」を有効にしてください
UserShellFolderNotEmpty                   = 一部のファイルが "{0}" フォルダーに残っています。ご自身で新しい場所に移動してください
RetrievingDrivesList                      = ドライブリストを取得しています...
DriveSelect                               = "{0}" フォルダーが作成されるルート内のドライブを選択してください
CurrentUserFolderLocation                 = 現在の "{0}" フォルダーの場所: "{1}"
UserFolderRequest                         = "{0}" フォルダーの場所を変更しますか？
UserDefaultFolder                         = "{0}" フォルダーの場所をデフォルトの値に変更しますか？
ReservedStorageIsInUse                    = 予約ストレージが使用中の場合、この操作はサポートされません\nPC の再起動後、"{0}" 関数を再度実行してください
ShortcutPinning                           = "{0}" ショートカットをスタートにピン留めしています...
SSDRequired                               = Windows Subsystem for Android™ を利用する場合は、お使いのデバイスに Solid State Drive (SSD) が組み込まれている必要があります
UninstallUWPForAll                        = 全てのユーザー
UWPAppsTitle                              = UWP アプリ
GraphicsPerformanceTitle                  = お好みのアプリのグラフィックパフォーマンス設定を「高パフォーマンス」に設定しますか？
ActionCenter                              = "{0}" 関数を利用するためにはアクションセンターを有効にする必要があります
WindowsScriptHost                         = このマシーンでは Windows Script Host へのアクセスが禁止されています。"{0}" 関数を実行するためには Windows Script Host を有効にしてください
S
ScheduledTaskPresented                    = "{0}" 関数は既に "{1}" として作成されています。
CleanupTaskNotificationTitle              = Windows クリーンアップ
CleanupTaskNotificationEvent              = Windows の使われてないファイルとアップデートのクリーンアップタスクを実行しますか
CleanupTaskDescription                    = ビルトインのディスククリーンアップアプリを使用して、Windows の使われてないファイルとアップデートをクリーンアップします
CleanupNotificationTaskDescription        = Windows の使われてないファイルとアップデートをクリーンアップした際のポップアップ通知
SoftwareDistributionTaskNotificationEvent = Windows アップデートのキャッシュを削除しました
TempTaskNotificationEvent                 = 一時ファイルのフォルダーをクリーンアップしました
FolderTaskDescription                     = {0} フォルダークリーンアップ
EventViewerCustomViewName                 = プロセスの作成
EventViewerCustomViewDescription          = プロセスの作成とコマンドラインの監視イベント
RestartWarning                            = 必ず PC を再起動してください
ErrorsLine                                = Line
ErrorsMessage                             = Error/Warning
DialogBoxOpening                          = ダイアログを表示します...
Disable                                   = 無効化
Enable                                    = 有効化
AllFilesFilter                            = 全てのファイル
FolderSelect                              = フォルダーを選択してください
FilesWontBeMoved                          = ファイルは移動されません
Install                                   = インストール
NoData                                    = 表示するものがありません
NoInternetConnection                      = インターネット接続がありません
RestartFunction                           = 再度 "{0}" 関数を実行してください
NoResponse                                = {0} への接続が確立できませんでした
Restore                                   = 復元
Run                                       = 実行
Skipped                                   = スキップされました
GPOUpdate                                 = GPO をアップデートしています...
TelegramGroupTitle                        = 私たちの公式 Telegram グループに参加してください
TelegramChannelTitle                      = 私たちの公式 Telegram チャンネルに参加してください
DiscordChannelTitle                       = 私たちの公式 Discord チャンネルに参加してください
Uninstall                                 = アンインストール
'@
