ConvertFrom-StringData -StringData @'
UnsupportedOSBuild                        = このスクリプトは Windows 11 21H2 かそれ以上のバージョンをサポートしています
UpdateWarning                             = お使いの Windows 11 は build: {0}.{1}です。サポートされているのは builds: 22000.739, 22621 かそれ以上です
UnsupportedLanguageMode                   = PowerShell は限られた言語モードで実行されています
LoggedInUserNotAdmin                      = ログオンしているユーザーには管理者権限がありません
UnsupportedPowerShell                     = PowerShell {0}.{1} でスクリプトを実行しようとしています。適切な PowerShell のバージョンで実行してください
UnsupportedISE                            = Windows PowerShell ISE でのスクリプトの実行はサポートされていません
Win10TweakerWarning                       = お使いの OS は Win 10 Tweaker のバックドアから感染した可能性があります
Windows10DebloaterWarning                 = Windos の安定性が Sycnex の Windows10Debloater スクリプトで損なわれた可能性があります。念のため、OS を再インストールしてください
bin                                       = bin フォルダーの中にファイルがありません。再度、アーカイブをダウンロードしてください
RebootPending                             = PC は再起動の待機中です
UnsupportedRelease                        = 新しいバージョンが見つかりました
CustomizationWarning                      = \nSophia Script を実行する前に {0} プリセットファイル内の各機能を好みに合わせて変更しましたか？
WindowsBroken                             = 一部の Windows コンポーネントが破損している可能性があります
ControlledFolderAccessDisabled            = 制御されたフォルダー アクセスが無効になっています
ScheduledTasks                            = スケジュールされたタスク
OneDriveUninstalling                      = OneDrive をアンインストールしています...
OneDriveInstalling                        = OneDrive をインストールしています...
OneDriveDownloading                       = OneDrive をダウンロードしています... ~33 MB
OneDriveWarning                           = "{0}" 関数は、OneDrive を削除するようプリセットで設定されている場合に限り適用されます（またはアプリが既に削除されている場合）、さもなければ、OneDrive 内の "デスクトップ" と "ピクチャ" フォルダーのバックアップ機能が停止します
WindowsFeaturesTitle                      = Windows の機能
OptionalFeaturesTitle                     = オプション機能
EnableHardwareVT                          = UEFI で「ハードウェアの仮想化」を有効にしてください
UserShellFolderNotEmpty                   = 一部のファイルが "{0}" フォルダーに残っています。ご自身で新しい場所に移動してください
RetrievingDrivesList                      = ドライブリストを取得しています...
DriveSelect                               = "{0}" フォルダーが作成されるルート内のドライブを選択してください
CurrentUserFolderLocation                 = 現在の "{0}" フォルダーの場所: "{1}"
UserFolderRequest                         = "{0}" フォルダーの場所を変更しますか？
UserFolderSelect                          = "{0}" フォルダーのためのフォルダーを選択してください
UserDefaultFolder                         = "{0}" フォルダーの場所をデフォルトの値に変更しますか？
ReservedStorageIsInUse                    = 予約ストレージが使用中の場合、この操作はサポートされません\nPC の再起動後、"{0}" 関数を再度実行してください
ShortcutPinning                           = "{0}" ショートカットはスタートにピン留めされています...
SSDRequired                               = Windows Subsystem for Android™ を利用する場合、お使いのデバイスに Solid State Drive (SSD) が組み込まれている必要があります
UninstallUWPForAll                        = 全てのユーザー
UWPAppsTitle                              = UWP アプリ
HEVCDownloading                           = デバイスの製造元から HEVC ビデオ拡張機能をダウンロードしています... ~2.8 MB
GraphicsPerformanceTitle                  = グラフィックパフォーマンスの設定
GraphicsPerformanceRequest                = お好みのアプリのグラフィックパフォーマンス設定を「高パフォーマンス」に設定しますか？
CleanupTaskNotificationTitle              = Windows クリーンアップ
CleanupTaskNotificationEvent              = Windows の使われてないファイルとアップデートのクリーンアップタスクを実行しますか
CleanupTaskDescription                    = ビルトインのディスククリーンアップアプリを使用して、Windows の使われてないファイルとアップデートをクリーンアップします
CleanupNotificationTaskDescription        = Windows の使われてないファイルとアップデートをクリーンアップした際のポップアップ通知
SoftwareDistributionTaskNotificationEvent = Windows アップデートのキャッシュを削除しました
TempTaskNotificationEvent                 = 一時ファイルのフォルダーをクリーンアップしました
FolderTaskDescription                     = {0} フォルダークリーンアップ
EventViewerCustomViewName                 = プロセスの作成
EventViewerCustomViewDescription          = プロセスの作成とコマンドラインの監視イベント
RestartWarning                            = 必ず PC を再起動してください
ErrorsLine                                = Line
ErrorsFile                                = File
ErrorsMessage                             = Error/Warning
Add                                       = 追加
AllFilesFilter                            = 全てのファイル (*.*)|*.*
Browse                                    = ブラウズ
DialogBoxOpening                          = ダイアログを表示します...
Disable                                   = 無効化
Enable                                    = 有効化
EXEFilesFilter                            = *.exe|*.exe|全てのファイル (*.*)|*.*
FolderSelect                              = フォルダーを選択してください
FilesWontBeMoved                          = ファイルは移動されません
Install                                   = インストール
NoData                                    = 表示するものがありません
NoInternetConnection                      = インターネット接続がありません
RestartFunction                           = 再度 "{0}" 関数を実行してください
NoResponse                                = {0} への接続が確立できませんでした
No                                        = No
Yes                                       = Yes
Open                                      = 開く
Patient                                   = 少々お待ちください...
Restore                                   = 復元
Run                                       = 実行
SelectAll                                 = 全て選択
Skipped                                   = スキップされました
GPOUpdate                                 = GPO をアップデートしています...
TelegramGroupTitle                        = 私たちの公式 Telegram グループに参加してください
TelegramChannelTitle                      = 私たちの公式 Telegram チャンネルに参加してください
DiscordChannelTitle                       = 私たちの公式 Discord チャンネルに参加してください
Uninstall                                 = アンインストール
'@

# SIG # Begin signature block
# SIG # End signature block
