startup = [
	"zoxide init nushell --hook prompt | save ~/.zoxide.nu",
	"source ~/.zoxide.nu",
	"mkdir ~/.cache/starship",
	"starship init nu | save ~/.cache/starship/init.nu",
	"source ~/.cache/starship/init.nu",

	"alias br = broot.exe",
	"alias code = codium",
	"alias cls = clear",
	"alias vim = nvim",
    "alias list = nvim ~/list.txt",
    "alias cfg = nvim ~/AppData/Local/nvim/init.vim",
    "alias nf = nvim ~/.config/nushell/config.toml",
    "alias mpf = nvim ~/scoop/persist/mpv/portable_config/mpv.conf",

    "def ppu [name] {python -m pip install -U $name}",

    "def gld [] {gallery-dl --config ~/.config/gallery-dl/config.json -i ~/list.txt}",
    "def aria [] {aria2c --conf-path ($nu.env.USERPROFILE + '/.config/aria2.conf') -d D:/Downloads -x16 -j16 -s16 -k1M -i ~/list.txt}",
    "def yt [category: string] {yt-dlp --config-location ('~/.config/yt-dlp/' + $category + '.conf')}",

	"def fzfp [] {fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'}",
	"def ll [] {lsd -l --blocks permission --blocks size --blocks date --blocks name --blocks inode}",
	"def lls [] {ls | where type != Symlink}",
    "def tree [ignore: string] {lsd --tree -I $ignore}",
    "def pdf [$target: string] {sumatrapdf -invert-colors $target}"
	]

prompt = "starship prompt"
complete_from_path = true
rm_always_trash = false
pivot_mode = "auto"  # auto, always, never

[line_editor]
max_history_size = 100000
history_duplicates = "ignoreconsecutive" # alwaysadd,ignoreconsecutive
history_ignore_space = false
completion_type = "circular" # circular, list, fuzzy
completion_prompt_limit = 100
keyseq_timeout_ms = 500 # ms
edit_mode = "vi" # vi, emacs
auto_add_history = true
bell_style = "audible" # audible, none, visible
color_mode = "enabled" # enabled, forced, disabled
tab_stop = 4

[textview]
term_width = "default" # "default" or a number
tab_width = 4
colored_output = true
true_color = true
header = true
line_numbers = true
grid = false
vcs_modification_markers = true
snip = true
wrapping_mode = "Character" # Character, NoWrapping
use_italics = true
paging_mode = "QuitIfOneScreen" # Always, QuitIfOneScreen, Never
pager = "less"
theme = "TwoDark"

[env]
_ZO_ECHO="1"
